#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
INVENTORY_DIR="$REPO_ROOT/docs/inventory"
LATEST="$INVENTORY_DIR/LATEST.md"
MODE="${1:---check}"

required=(
	"AGENTS.md"
	"CLAUDE.md"
	"PROJECT.md"
	"docs/CHECKPOINT-PROCESS.md"
	"docs/CURRENT-STATE.md"
	"docs/DEPLOYMENT.md"
	"docs/DATA-MODEL.md"
	"docs/OPERATIONS.md"
	"docs/DECISIONS.md"
	"docs/HANDOFF.md"
)

fail=0
for path in "${required[@]}"; do
	if [[ ! -s "$REPO_ROOT/$path" ]]; then
		echo "error: required shared-memory file is missing or empty: $path" >&2
		fail=1
	fi
done

if [[ "$MODE" == "--check" ]]; then
	if [[ ! -s "$LATEST" ]]; then
		echo "error: generated inventory is missing; run $0 --write" >&2
		fail=1
	fi
	if git -C "$REPO_ROOT" ls-files | grep -E '(^|/)(Codes|photos|snapshots|backups)/|\.csv$|settings\.local\.json$' >/dev/null; then
		echo "error: a prohibited local/customer artifact is tracked" >&2
		fail=1
	fi
	if git -C "$REPO_ROOT" grep -nEI \
		'(BEGIN (RSA |OPENSSH )?PRIVATE KEY|password[[:space:]]*[:=][[:space:]]*[^<$[:space:]]|api[_-]?key[[:space:]]*[:=][[:space:]]*[A-Za-z0-9]|SYNC_SECRET[[:space:]]*=[[:space:]]*['"'"'"][^$<{])' \
		-- ':!scripts/project-checkpoint.sh' >/dev/null; then
		echo "error: tracked content matches a high-confidence secret pattern; review git grep output locally" >&2
		fail=1
	fi
	if [[ $fail -ne 0 ]]; then
		exit 1
	fi
	echo "Shared-memory structure and tracked-file safety checks passed."
	exit 0
fi

if [[ "$MODE" != "--write" ]]; then
	echo "Usage: $(basename "$0") --write|--check" >&2
	exit 2
fi

if [[ $fail -ne 0 ]]; then
	exit 1
fi

mkdir -p "$INVENTORY_DIR"
checkpoint_date="$(date +%Y-%m-%d)"
snapshot="$INVENTORY_DIR/$checkpoint_date.md"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
	echo "# Repository inventory"
	echo
	echo "Generated: $checkpoint_date"
	echo
	echo "> Mechanical snapshot generated by \`scripts/project-checkpoint.sh\`."
	echo "> Review the human-authored project documents for production status and context."
	echo
	echo "## Git"
	echo
	echo "- Branch: \`$(git -C "$REPO_ROOT" branch --show-current)\`"
	echo "- HEAD: \`$(git -C "$REPO_ROOT" rev-parse --short HEAD)\` — $(git -C "$REPO_ROOT" log -1 --pretty=%s)"
	echo "- Remote: \`$(git -C "$REPO_ROOT" remote get-url origin 2>/dev/null || echo 'not configured')\`"
	echo
	echo "## Tracked components"
	echo
	for file in "$REPO_ROOT"/*/*.php; do
		[[ -f "$file" ]] || continue
		name="$(sed -n 's/^[[:space:]]*\*[[:space:]]*Plugin Name:[[:space:]]*//p' "$file" | head -1)"
		version="$(sed -n 's/^[[:space:]]*\*[[:space:]]*Version:[[:space:]]*//p' "$file" | head -1)"
		[[ -n "$name" ]] || continue
		echo "- \`${file#"$REPO_ROOT/"}\`: $name ${version:+(v$version)}"
	done
	echo "- \`scores-site/index.html\`: static scores placeholder"
	echo
	echo "## Tracked files"
	echo
	echo '```text'
	git -C "$REPO_ROOT" ls-files | sort
	echo '```'
	echo
	echo "## Working-tree classification"
	echo
	echo "Run \`git status --short\` locally for exact current changes. Untracked"
	echo "customer exports, codes, photos, snapshots, ZIPs, secrets, and local"
	echo "settings are deliberately excluded from this inventory."
	echo
	echo "## Recent commits"
	echo
	git -C "$REPO_ROOT" log -10 --pretty='- `%h` %s'
} >"$tmp"

cp "$tmp" "$LATEST"
cp "$tmp" "$snapshot"
echo "Wrote docs/inventory/LATEST.md and docs/inventory/$checkpoint_date.md"
